[package]
authors = ["BarbossHack <barbossh4ck@protonmail.com>"]
edition = "2021"
name = "shmap"
version = "0.1.0"

[dependencies]
# is bincode really faster than bson ?
bincode = {version = "2.0.0-rc", features = ["serde"]}
libc = "0.2"
memmap2 = "0.5"
named-lock = "0.1"
serde = "1.0"
sha2 = "0.10"
thiserror = "1.0"

[dev-dependencies]
rand = "*"
